name: CI-CD Workflow

on:
  push:
    branches:
      - "main"
    tags:
      - "release-*"

jobs:
  test-asan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++

    - name: Configure CMake
      run: cmake --preset=ci-asan -DPROJECT_VERSION_PATCH=${{ github.run_number }}

    - name: Build
      run: cmake --build --preset=ci-asan

    - name: Test
      run: ctest --preset=ci-asan

  test-tsan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++

    - name: Configure CMake
      run: cmake --preset=ci-tsan -DPROJECT_VERSION_PATCH=${{ github.run_number }}

    - name: Build
      run: cmake --build --preset=ci-tsan

    - name: Test
      run: ctest --preset=ci-tsan

  release:
    runs-on: ubuntu-latest
    needs: [test-asan, test-tsan]
    if: startsWith(github.ref, 'refs/tags/release-')

    steps:
    - uses: actions/checkout@v4

    - name: Install DEB tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++

    - name: Configure CMake
      run: cmake --preset=release -DPROJECT_VERSION_PATCH=${{ github.run_number }}

    - name: Build
      run: cmake --build --preset=release

    - name: Create DEB package
      run: cpack --preset release

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload DEB package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/release/helloworld-0.0.${{ github.run_number }}-Linux.deb
        asset_name: helloworld-0.0.${{ github.run_number }}-Linux.deb
        asset_content_type: application/vnd.debian.binary-package