name: build and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build g++

    - name: Configure CMake
      run: cmake --preset=release -DPROJECT_VERSION_PATCH=${{ github.run_number }}

    - name: Build
      run: cmake --build --preset=release

    - name: Test
      run: ctest --preset=release